[package]
name = "libre-url2audio-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5.13"
curl = "0.4.46"
libpulse-binding = "2.28.1"
libpulse-simple-binding = "2.28.1"
symphonia = { version = "0.5.4", features = ["all", "opt-simd"] }
ureq = "2.9.7"
